### PR TITLE
Fix Ci tests and update packaging

### PR DESCRIPTION
**Pull request by liZe**
This PR cleans and updates CI, tests and packaging.

**CI has been fixed,** with tests launched on officially supported versions of Python. Tests are launched on latest versions Windows, macOS and Ubuntu using the latest version of Python (3.12 now). They’re also launched on Ubuntu for the lowest supported version of Python (3.8 now) and PyPy (3.8). Tests now fail as soon as one of these steps fails.

**Packaging has been updated** using recent best practices from [the Python Packaging Authority (PyPA)](https://www.pypa.io/). `setup.py`, `setup.cfg`, `tox.ini` and `MANIFEST.in` have been merged into a single `pyproject.toml` file. Packaging is done using [Hatchling](https://pypi.org/project/hatchling/), as suggested by the PyPA by default.

Hatchling follows the standard way of building packages, it works well with `build` and `twine`. The generated source and wheel packages are equivalent to the ones currently available on PyPI for Frozen-Flask, they work well as far as I can tell 😄, and they’re a bit smaller.

The only change that’s been required on the repository structure is the removal of the `artworks` soft link, as links don’t work in packages and Hatchling doesn’t want to include the files twice. Artwork is still available in the `docs` folder.

As [calling `setup.py` directly has been deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html), it’s not possible anymore to use it to build docs or launch tests. It’s now possible to use [Hatch](https://hatch.pypa.io/latest/), the high-level command-line tool that comes on top of Hatchling. Hatch takes care of installing dependencies, creating virtual environments and calling the related commands with the right options. It also gives commands to build and upload packages. Of course, it’s still possible to launch all these commands manually, if some users don’t want to use Hatch.

Tox’ configuration has also been updated to use recent versions of Python. A target to test Flask 2.0.0 has also been added, even if it’s not launched by the CI (I’m not yet sure about the "right" way to do this).

The next steps I’d like to do before releasing a new version is:
- to update the documentation;
- to update and clean the code (at least to remove the Python 2 support code, and to follow PEP8).

I’ll open separate PRs for these!

### CODE REVIEW

**Review by tswast — APPROVED** [review]
Thanks!

**Comment by krystalgamer** [comment]
@tswast would it be possible to merge this? I require these changes for my personal blogging tool.

**Comment by liZe** [comment]
> @tswast would it be possible to merge this? I require these changes for my personal blogging tool.

Would you like it to be released or just merged? I’d like to update the code (almost done) and to clean the documentation before releasing a new version.

**Comment by krystalgamer** [comment]
the preferred option would be a new release but so far I've managed to freeze older package versions and it's now working like a charm. no pressure, if you need any help I'm open to help! this package has helped me so much!

**Comment by liZe** [comment]
We can at least merge this PR, it’s been open to review for some time no and nobody complained 😄.

> no pressure, if you need any help I'm open to help!

The problem I currently have is that I get **random** errors on #134 with PyPy, like in [this job](https://github.com/Frozen-Flask/Frozen-Flask/actions/runs/6738831868/job/18319190334). If anyone has some experience with PyPy, that would be helpful!

**Comment by davidism** [comment]
@liZe Just wanted to say I really appreciate these explanations you've written in your PRs, and the work you've done to update Frozen-Flask. If you're interested in getting more community maintainer support, I'm slowly starting up [pallets-eco](https://github.com/pallets-eco) to collect community extensions, similar to [JazzBand](https://github.com/jazzband). You can message us in [Pallets Discord](https://discord.gg/pallets) about it.

**Pull request merged**
