### PR TITLE
Add support for Flask 3.0

### LINKED ISSUE #129: Frozen-Flask is not compatible with Werkzeug 3.0.0
I was using `freeze.freeze()` and I got the following issue: `AttributeError: 'Map' object has no attribute 'charset'`
After looking at the Werkzeug documentation, I saw that `charset` has been deprecated.

### LINKED ISSUE #131: AttributeError: 'Map' object has no attribute 'charset'
I have a flask application that is serving a single route `/` in the  file `app.py` which looks as follows:

```shell
from flask import Flask, render_template
app = Flask(__name__)
@app.route("/", methods=["GET"])
def home():
    return render_template("index.html")
if __name__ == "__main__":
    app.run(host="localhost", port=1234, debug=True)
```

Now when i try to build this app by running the command:

```shell
python build.py
```
Where as the build.py file looks as follows:

```py
from app import app
from flask_frozen import Freezer

freezer = Freezer(app=app, with_static_files=True)
if __name__ == '__main__':
    freezer.freeze()
```

I'm getting the error that says:

```shell
site-packages\flask_frozen\__init__.py", line 232, in _generate_all_urls
    url_encoding = self.app.url_map.charset
                   ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Map' object has no attribute 'charset'
```

What maybe possibly the problem here:

### PR DESCRIPTION
**Pull request by liZe**
@tswast This PR fixes two problems with recent versions of Werkzeug and Flask:

- The `charset` attribute has been deprecated in Werkzeug 2.3.0 and removed in 3.0.0. It’s now always set to `utf-8`.
- The `send_static_file` methods are now different in `Flask` and `Blueprint`, but thanks to a very valuable assert + comment it was a piece of cake to debug and fix.

The first point may look frightening (as discussed in #130 too), but this `charset` attribute was more an old artefact of the Python 2 to 3 port of Werkzeug than a real supported feature, according to the [changelog](https://werkzeug.palletsprojects.com/en/3.0.x/changes/#version-2-3-0) and the [related issue](https://github.com/pallets/werkzeug/issues/2602). From what I can understand, it looks frightening but it’s actually quite safe.

Tests now pass with Flask 3 and Werkzeug 3. I’d like to check a couple of things before proposing to merge this PR, like testing with Flask 2.x and real applications.

Fix #129, fix #131. Includes the same fix as #130.

(I’ll take care of the CI in another PR, as it’s unrelated.)

### CODE REVIEW

**Comment by liZe** [comment]
I’ve tested with previous versions of Flask and Werkzeug, and it works at least with Flask 2.0.0 (1.x support is supposed to work according to the package dependencies, but it doesn’t, even without this PR).

I’ve also tested some of my projects and it seems to work well.

**Comment by liZe** [comment]
Let’s merge this!

If anyone wants to review #133 (with a lot of changes), I’ll let it open for a few days.

**Comment by jpmckinney** [comment]
Not to be a 🐛 but would you know the timeline for releasing 3.0 support?

**Comment by jpmckinney** [comment]
Nevermind - 0.19 is released, `pip-compile` was just being a dummy and needed `--resolver=backtracking`.

**Comment by liZe** [comment]
> Not to be a 🐛 but would you know the timeline for releasing 3.0 support?

Probably later this week. Feedback is welcome for #134 if you want to help!

**Pull request merged**
