### PR TITLE
Clean code

### LINKED ISSUE #63: Project should pass flake8 linter
- [ ] Add flake8 to a requirements-dev.txt file (not a package dependency).
- [ ] Fix current flake8 warnings and errors.
- [ ] Add flake8 to Travis builds.

<details>
<summary>

Output from <code>flake8</code> command</summary>

<pre>./setup.py:5:80: E501 line too long (80 > 79 characters)
./docs/conf.py:6:80: E501 line too long (80 > 79 characters)
./docs/conf.py:14:11: E401 multiple imports on one line
./docs/conf.py:19:1: E265 block comment should start with '# '
./docs/conf.py:22:80: E501 line too long (80 > 79 characters)
./docs/conf.py:25:1: E265 block comment should start with '# '
./docs/conf.py:27:80: E501 line too long (80 > 79 characters)
./docs/conf.py:41:1: E265 block comment should start with '# '
./docs/conf.py:55:1: E265 block comment should start with '# '
./docs/conf.py:56:1: E402 module level import not at top of file
./docs/conf.py:65:1: E265 block comment should start with '# '
./docs/conf.py:69:1: E265 block comment should start with '# '
./docs/conf.py:71:1: E265 block comment should start with '# '
./docs/conf.py:77:80: E501 line too long (80 > 79 characters)
./docs/conf.py:78:1: E265 block comment should start with '# '
./docs/conf.py:81:1: E265 block comment should start with '# '
./docs/conf.py:85:1: E265 block comment should start with '# '
./docs/conf.py:89:1: E265 block comment should start with '# '
./docs/conf.py:92:1: E265 block comment should start with '# '
./docs/conf.py:95:1: E265 block comment should start with '# '
./docs/conf.py:98:80: E501 line too long (80 > 79 characters)
./docs/conf.py:107:1: E265 block comment should start with '# '
./docs/conf.py:111:1: E122 continuation line missing indentation or outdented
./docs/conf.py:119:1: E265 block comment should start with '# '
./docs/conf.py:122:1: E265 block comment should start with '# '
./docs/conf.py:126:1: E265 block comment should start with '# '
./docs/conf.py:131:1: E265 block comment should start with '# '
./docs/conf.py:140:1: E265 block comment should start with '# '
./docs/conf.py:144:1: E265 block comment should start with '# '
./docs/conf.py:151:1: E265 block comment should start with '# '
./docs/conf.py:154:1: E265 block comment should start with '# '
./docs/conf.py:157:1: E265 block comment should start with '# '
./docs/conf.py:160:1: E265 block comment should start with '# '
./docs/conf.py:163:1: E265 block comment should start with '# '
./docs/conf.py:166:1: E265 block comment should start with '# '
./docs/conf.py:169:1: E265 block comment should start with '# '
./docs/conf.py:174:1: E265 block comment should start with '# '
./docs/conf.py:177:1: E265 block comment should start with '# '
./docs/conf.py:183:80: E501 line too long (80 > 79 characters)
./docs/conf.py:186:1: E265 block comment should start with '# '
./docs/conf.py:189:1: E265 block comment should start with '# '
./docs/conf.py:192:80: E501 line too long (80 > 79 characters)
./docs/conf.py:200:1: E265 block comment should start with '# '
./docs/conf.py:204:1: E265 block comment should start with '# '
./docs/conf.py:207:1: E265 block comment should start with '# '
./docs/conf.py:210:1: E265 block comment should start with '# '
./docs/conf.py:213:1: E265 block comment should start with '# '
./docs/conf.py:216:1: E265 block comment should start with '# '
./docs/conf.py:219:1: E265 block comment should start with '# '
./docs/conf.py:222:80: E501 line too long (80 > 79 characters)
./flask_frozen/__init__.py:20:1: E402 module level import not at top of file
./flask_frozen/__init__.py:21:1: E402 module level import not at top of file
./flask_frozen/__init__.py:22:1: E402 module level import not at top of file
./flask_frozen/__init__.py:23:1: E402 module level import not at top of file
./flask_frozen/__init__.py:24:1: E402 module level import not at top of file
./flask_frozen/__init__.py:25:1: E402 module level import not at top of file
./flask_frozen/__init__.py:26:1: E402 module level import not at top of file
./flask_frozen/__init__.py:27:1: E402 module level import not at top of file
./flask_frozen/__init__.py:28:1: E402 module level import not at top of file
./flask_frozen/__init__.py:29:1: E402 module level import not at top of file
./flask_frozen/__init__.py:30:1: E402 module level import not at top of file
./flask_frozen/__init__.py:37:1: E402 module level import not at top of file
./flask_frozen/__init__.py:37:1: F401 'werkzeug.exceptions.HTTPException' imported but unused
./flask_frozen/__init__.py:38:1: E402 module level import not at top of file
./flask_frozen/__init__.py:55:1: E302 expected 2 blank lines, found 1
./flask_frozen/__init__.py:58:1: E302 expected 2 blank lines, found 1
./flask_frozen/__init__.py:61:1: E302 expected 2 blank lines, found 1
./flask_frozen/__init__.py:285:67: E502 the backslash is redundant between brackets
./flask_frozen/__init__.py:286:21: E128 continuation line under-indented for visual indent
./flask_frozen/__init__.py:303:80: E501 line too long (80 > 79 characters)
./flask_frozen/__init__.py:304:80: E501 line too long (81 > 79 characters)
./flask_frozen/__init__.py:429:48: E272 multiple spaces before keyword
./flask_frozen/tests.py:24:5: E128 continuation line under-indented for visual indent
./flask_frozen/tests.py:25:5: E128 continuation line under-indented for visual indent
./flask_frozen/tests.py:106:13: E131 continuation line unaligned for hanging indent
./flask_frozen/tests.py:162:13: E261 at least two spaces before inline comment
./flask_frozen/tests.py:307:35: E127 continuation line over-indented for visual indent
./flask_frozen/tests.py:331:35: E127 continuation line over-indented for visual indent
./flask_frozen/tests.py:345:35: E127 continuation line over-indented for visual indent
./flask_frozen/tests.py:358:35: E127 continuation line over-indented for visual indent
./flask_frozen/tests.py:377:13: E301 expected 1 blank line, found 0
./flask_frozen/tests.py:385:13: E301 expected 1 blank line, found 0
./flask_frozen/tests.py:393:35: E127 continuation line over-indented for visual indent
./flask_frozen/tests.py:407:80: E501 line too long (81 > 79 characters)
./flask_frozen/tests.py:432:1: E303 too many blank lines (3)
./flask_frozen/tests.py:457:54: E231 missing whitespace after ','
./flask_frozen/test_app/__init__.py:63:80: E501 line too long (82 > 79 characters)
./flask_frozen/test_app/__init__.py:73:5: F811 redefinition of unused 'product' from line 65
./flask_frozen/test_app/admin/__init__.py:15:5: E128 continuation line under-indented for visual indent
./flask_frozen/test_app/admin/__init__.py:16:5: E128 continuation line under-indented for visual indent
</pre>

</details>

### LINKED ISSUE #112: Update to Flask 2.0 and drop Python 2.7
Flask 2.0 was recently released. https://palletsprojects.com/blog/flask-2-0-released/

This release drops support for Python 2.7 and Python 3.5, which should simplify our tests.

### PR DESCRIPTION
**Pull request by liZe**
- Drop Python 2 and old Python 3 versions support (fix #112).
- Use recent standard libraries and syntaxes.
- Use Pytest instead of `unittest`.
- Use Hatch instead of Tox to launch tests with different versions of Python and Flask.
- Use Hatch in CI to launch tests.
- Follow PEP-8 (fix #63) and PEP-257.

### CODE REVIEW

**Comment by liZe** [comment]
Tests pass, but we get random failures with PyPy. 😡

**Comment by krystalgamer** [comment]
just to be sure PyPy fails with all of these PR changes or fails even with what's on master branch?

**Comment by liZe** [comment]
> just to be sure PyPy fails with all of these PR changes or fails even with what's on master branch?

No idea to be honest, because these failures happen randomly. We should try to launch tests on a local computer with PyPy, multiple times, with the current master branch.

**Comment by liZe** [comment]
The same problem occurs with Frozen-Flask 0.18, it’s not been introduced by this PR.

**Comment by liZe** [comment]
> The same problem occurs with Frozen-Flask 0.18, it’s not been introduced by this PR.

It’s hard to tell if it’s a bug in Flask, Frozen-Flask, Frozen-Flask tests or PyPy. By the way, I suspect that it’s been broken with PyPy for a very long time, so let’s just drop official support of PyPy.

**Comment by liZe** [comment]
Real-world tests are welcome!

**Comment by jpmckinney** [comment]
Re: PyPy do the tests ever use multiple threads? That's a scenario where `Popped wrong app context.` can occur. That said, I won't miss it.

Otherwise, the PR looks good. The pathlib commit is a bit harder for me to review. Instead, I ran this branch in my project and the output is correct.

**Comment by liZe** [comment]
> Re: PyPy do the tests ever use multiple threads? That's a scenario where `Popped wrong app context.` can occur. That said, I won't miss it.

No idea, but that’s possible. As tests didn’t pass before this PR with the same random error, I suppose that nobody will actually miss this "official" support.

> Instead, I ran this branch in my project and the output is correct.

Good to know, thanks!

**Pull request merged**
