### PR TITLE
Guard against .charset removal

### PR DESCRIPTION
**Pull request by honzajavorek**
Possibly a fix of https://github.com/Frozen-Flask/Frozen-Flask/issues/129, but I made it by pencil here on GitHub, didn't really test it out properly.

### CODE REVIEW

**Comment by paulocoutinhox** [comment]
Hey guys, wake up. We need a fix!

**Comment by hroncok** [comment]
Paulo. I am one of the people who probably have right to commit to this project. In fact, I was planning to have a look after I deal with my broken car, with my sick cat and with my job. I will assume the demanding attitude is not something you've used deliberately, but rather a language barrier. I kindly ask you to consider the tone of your comments.

**Comment by hroncok** [comment]
https://github.com/pallets/werkzeug/issues/2602 indicates that we should always indeed be working with utf-8, but I wonder if this does not break stuff here.

**Comment by paulocoutinhox** [comment]
> Paulo. I am one of the people who probably have right to commit to this project. In fact, I was planning to have a look after I deal with my broken car, with my sick cat and with my job. I will assume the demanding attitude is not something you've used deliberately, but rather a language barrier. I kindly ask you to consider the tone of your comments.

I don't know what you understand. I only call attention to do a fix, because this project has old commits, not answered prs and builds are failed on readme, so it appear that it is abandoned or not yet maintained anymore.

**Comment by honzajavorek** [comment]
> it is abandoned or not yet maintained anymore

That is mostly true. There are no active maintainers I'd know about, but there are a few people with commit rights, who might want to work on fixing this and cut a release, if they feel like doing it. I'm one of those people and I made this Pull Request as a kick off. There is a chance that I'll continue, or that @hroncok or @SimonSapin get the pass and run with the ball, but I leave it up to the entropy of our lives if that actually happens or not.

> this project has old commits, not answered prs and builds are failed on readme

I don't want to judge your decisions, but in such case it's usually better to migrate to a different project with active maintainers, than to demand a fix on people who are burned out or just doing something else at the moment. Believe me that those who are behind the project do know that builds are failing and fixes are not getting fixed. It's just at the bottom of their priorities. The [license](https://github.com/Frozen-Flask/Frozen-Flask/blob/master/LICENSE) says there's no warranty.

If you happen to be in a situation in which you cannot use a different project, then it's apparently higher on the list of your priorities then on ours and you or your organization are the ones who should do something about it:

- Fork the project and maintain it. Either only for you, or for others, too - as you like. The [license](https://github.com/Frozen-Flask/Frozen-Flask/blob/master/LICENSE) says that you are free to do so.
- Find a different solution and migrate (e.g. browse this https://jamstack.org/generators/ )
- Pin werkzeug in your dependencies to version < 3 until we find time and resolve this. Do you really _need_ to be on the bleeding edge?

> I only call attention to do a fix

The way you formulated it seemed like you demand us to do a fix. Let me put it like this: You do not pay for the software. You should be grateful it exists and be supportive, perhaps put your own work into a solution, not demand fixes done in other people's free time.

**Comment by paulocoutinhox** [comment]
Wow, are you guys making a big deal just because I asked for a fix? I didn't force anyone to do anything or put a gun to anyone's head. I'm trying to find a solution like everyone else. If no one wants to do it, just say you won't do it and I'll find another solution, you just don't have to cry over a message, for God's sake. I also have a life and several open source projects, that doesn't mean I treat people like that. Anyway, do as you prefer, or don't do it, I don't know.

**Comment by liZe** [comment]
The fix has been included in #132.

**Pull request closed without merging**
