### PR TITLE
Add info about maintainers

### PR DESCRIPTION
**Pull request by honzajavorek**
Would you @tswast and @SimonSapin be okay with this? I don't know if it's 100% correct, I just wrote down my long-term observations.

### CODE REVIEW

**Comment by SimonSapin** [comment]
This seems like the typical example of information that may easily becomes out of date but not updated. Why write it down in the first place?

**Comment by honzajavorek** [comment]
I wanted to set the right expectations to users. Also there have been people who were wondering whether they can become maintainers and didn't know who exactly to contact.

**Comment by honzajavorek** [comment]
If it's out of date, that would mean I have less time (in which case the text still sets quite correct expectations, e.g. that PR review can take weeks), or that the project has more or more active maintainers. In such case it at least documents how it was previously and I expect they'd update the text 🙂 or surprise contributors by over-delivering on how fast they react, which wouldn't be such a problem.

**Review by tswast — APPROVED** [review]
Looks about right to me. 😆

**Pull request merged**
